module.exports = {
  REPO_DOES_NOT_EXISTS: 'REPO_DOES_NOT_EXISTS',
  HACKING_ATTEMPT: 'HACKING_ATTEMPT',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  REPOS_DIR_NOT_EXISTS: 'REPOS_DIR_NOT_EXISTS',
  REPO_ALREADY_EXISTS: 'REPO_ALREADY_EXISTS',
  INVALID_GIT_REPO_URL: 'INVALID_GIT_REPO_URL',
  BRANCH_OR_COMMIT_DOES_NOT_EXISTS: 'BRANCH_OR_COMMIT_DOES_NOT_EXISTS',
  BRANCH_OR_COMMIT_OR_PATH_DOES_NOT_EXISTS: 'BRANCH_OR_COMMIT_OR_PATH_DOES_NOT_EXISTS',
  IS_NOT_A_DIRECTORY: 'IS_NOT_A_DIRECTORY',
  TIMEOUT_EXCEEDED: 'TIMEOUT_EXCEEDED',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR'
}