module.exports = {
  REPO_DOES_NOT_EXISTS: 'REPO_DOES_NOT_EXISTS',
  HACKING_ATTEMPT: 'HACKING_ATTEMPT',
  REPOS_DIR_NOT_EXISTS: 'REPOS_DIR_NOT_EXISTS',
  REPO_ALREADY_EXISTS: 'REPO_ALREADY_EXISTS',
  INVALID_GIT_REPO_URL: 'INVALID_GIT_REPO_URL',
  TIMEOUT_EXCEEDED: 'TIMEOUT_EXCEEDED'
}